# build stage
FROM python:3.9-alpine as build-stage
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .

# production stage
FROM python:3.9-alpine as production-stage
WORKDIR /app
COPY --from=build-stage /app .
EXPOSE 8080
CMD ["uvicorn", "main:app", "--port", "8080"]