version: "3.9"

services:
    frontend:
        container_name: frontend
        restart: on-failure
        image: mtas-frontend:latest
        build: ./frontend
        ports:
            - "80:80"

    transit_visualizer:
        container_name: micro-tv
        restart: always
        image: mtas-micro-tv:latest
        build: ./services/TransitVisualizer
        ports:
            - "5001:80"
