version: "3.9"

services:
    frontend:
        container_name: frontend
        image: mtas-frontend:latest
        build: ./frontend
        ports:
            - "80:80"
        depends_on:
            - backend

    backend:
        container_name: backend
        image: mtas-backend:latest
        build: ./backend
        ports:
            - "8080:8080"

    services:
        container_name: bridge
        image: rabbitmq:3.12-rc-alpine
        ports:
            - "5672:5672"
            - "15672:15672"
