version: "3.9"

services:
    frontend:
        container_name: frontend
        restart: on-failure
        image: mtas-frontend:latest
        build: ./frontend
        ports:
            - "80:80"

    backend:
        container_name: backend
        restart: on-failure
        image: mtas-backend:latest
        build: ./backend
        ports:
            - "8080:8080"
        depends_on:
            broker:
                condition: service_healthy

    broker:
        container_name: broker
        restart: always
        image: rabbitmq:3.12-rc-alpine
        ports:
            - "5672:5672"
            - "15672:15672"
        healthcheck:
            test: rabbitmq-diagnostics check_port_connectivity
            interval: 1s
            timeout: 3s
            retries: 30

    transit_visualizer:
        container_name: tv-service
        restart: always
        image: mtas-tv-service:latest
        build: ./services/TransitVisualizer/TransitVisualizer
        depends_on:
            broker:
                condition: service_healthy
